name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Set up Python
      if: ${{ matrix.os != 'ubuntu-latest' || matrix.python-version != '3.10' }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python 3.10 on Windows
      if: ${{ matrix.os == 'windows-latest' && matrix.python-version == '3.10' }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install flake8 and unittest
      run: |
        python -m pip install flake8
        python -m pip install -r requirements.txt

    - name: Display Python version
      run: |
        python --version

    - name: Run flake8
      run: |
        flake8 .

    - name: Run unittest
      run: |
        python -m unittest discover -v
